### ISSUE TITLE
Replace mysql_connect() by PDO

### ISSUE THREAD

**Issue by SaptakS** [GeekHaven/ProfileServer#15]
- mysql_connect() has been deprecated by PHP. 
- Most of the new versions of PHP won't have mysql_connect() modules anymore. 
- Moreover mysql_connect() has many security problems including mysql injection vulnerability which PDO handles perfectly.

So please update the code to PDO.

**Comment by shubham-padia** [comment]
@SaptakS Updated the code from mysql_connect to PDO in  #17
