### ISSUE TITLE
Fields to be included in the profile page

### ISSUE THREAD

**Issue by shubham-padia** [GeekHaven/ProfileServer#18]
@CosmicCoder96 @BelieveC @aditya19496 @dewana-dewan Add additions , deletions and suggestions please.

**What details of the student should be displayed in the user profile page ?**

It can Include :
(a profile photo and a cover photo also included)
1. Full Name
2. Roll No. 
3. Course
    -Degree
    -Specialization
4. Batch
5. Graduation Year (optional)
6.Date Of Birth(optional)
7. Skills (optional)
8. Images(1 image allowed)(optional)
9. About Me ( text description ) 
10.My Projects ( text decription) (optional)
11. Contact No.(optional)
12.Links to Social Site Profile  (Facebook, Google, LinkedIn ,Github , 1st additional link to be chosen by user with a generic logo ,2nd additional link to be chosen by user with a generic logo)(optional)
13. Resume (pdf format only)(optional)
14.E - mail (not the iiita one)

**Comment by BelieveC** [comment]
@shubham-padia ,I think Privacy Issues would pop up for DOB, Contact No .

**Comment by adewan-ai** [comment]
@BelieveC We could keep these optional.
@shubham-padia I think this list contains all the required details for a student. We will also need a separate profile page for the teacher.

**Comment by shubham-padia** [comment]
@BelieveC @dewana-dewan optional fields  are updated , suggest changes wherever required

**Comment by adewan-ai** [comment]
@shubham-padia The above list seems fine.
I will do the front end for this.

**Comment by hackerkid** [comment]
1 image is more than enough for profile server. No need of extending it to 4. `Course` should have two fields. Specialization (I.T, E.C etc) and Degree (B.Tech, M.Tech, PHD etc - Dropdown or Autocomplete). I am not sure about adding `skills`. There is linkedin for stuff like that. Make sure the `email` filled by the user is not the iiita mail (which can be recovered from rollno anyway). It would be useful for getting in touch once they graduate. And regarding the doc format. No one submits resume as .doc file. Do more research on that.

**Comment by shubham-padia** [comment]
Updated the list . @hackerkid  the `skills` field is completely optional and provides the user an option to display his skills in a more arranged manner, its upto the user whether to include it in his profile page or not.

**Comment by adewan-ai** [comment]
![image](https://cloud.githubusercontent.com/assets/15344309/16749145/cf1b8e4e-47e5-11e6-9450-15f142ad1a1b.png)

![image](https://cloud.githubusercontent.com/assets/15344309/16749149/dc0277f8-47e5-11e6-9e00-0e93040f3881.png)

![image](https://cloud.githubusercontent.com/assets/15344309/16749212/3291c68c-47e6-11e6-8816-4d36fed9811e.png)

![image](https://cloud.githubusercontent.com/assets/15344309/16749498/531d1378-47e8-11e6-8d93-f64cb0feb17c.png)

![image](https://cloud.githubusercontent.com/assets/15344309/16749175/083e3aa0-47e6-11e6-9015-310b6b278bd1.png)

This is how it looks as of now, 
Let me know what you people think and how this can be made better.
@shubham-padia @BelieveC @hackerkid

**Comment by shubham-padia** [comment]
@dewana-dewan  In my opinion, looks great 😄 .  I think we should remove the uppermost navbar ( the one with options,subjects, followers and friends) , as we will not be having any followers or friends , and we can have options in the upper-right settings icon . If required, other small changes can be made once the pages are added in the repo.
