### ISSUE TITLE
attendace layout

### ISSUE THREAD

**Issue by abhinavk96** [GeekHaven/ProfileServer#2]
Right now I'm making the attendace page, I am following the following layout:
- the teacher, after logging in can access this page.
-  there will be a dropdown to select the course , batch, section and Date
- after selecting all those things it will direct itself to a list of students in that section, where all will be marked present by default, unless marked absent.

Any other major features which should be integreated, please let me know.

**Comment by BelieveC** [comment]
I think we should let teacher select courses and respective Batches Once. They shouldn't need select and course each day for attendance. It would be like they add courses of respective once and can have listed them on Dashboard for ease of Access. We would require extra page for Course selection and Editing them later bt I feel it is worth giving a shoot. What do u think about this @CosmicCoder96

**Comment by abhinavk96** [comment]
yeah that's fine we will make only those course available in the drop downs , which the teacher has added to his profile. @BelieveC

**Comment by BelieveC** [comment]
Instead of Dropdown We can List them on Dashboard Page for Better UI. They would directly click to redirect to take attendance @CosmicCoder96  or any better idea u have?

**Comment by abhinavk96** [comment]
yeah okay

**Comment by aditya-kumawat** [comment]
i guess we need to let the teacher select the course everytime because he will be teaching more than one courses everyday and to differnet section.
Suggestion : 
We can let teacher give his timetable and according to it we can by default give him the attendance of that course or section at that time.

**Comment by BelieveC** [comment]
@aditya19496 Suggestion:  Sir, even though teacher will be teaching more than one courses everyday and to different section. He will have only some specific section and course for a whole week. So when he would select his desired courses at start of semester he won't need to do repeated stuff everyday if we list selected courses on Dashboard

**Comment by abhinavk96** [comment]
right now for maintaining attendance I am using the following setup.
shubham has made a separate user table which contains the details of all the users.
I am in turn creating a new table for **each** student. whihch will have the following columns:
- Date
- Subject1
- Subject2
- Subject3
- ...
- .
- so on

there will be three possible states .. for each column, P for present, A for absent and NC for no class
By default the value will be set to No class. and when the teacher will submit the attendance , these records will get updated , and will in turn be reflected on the student's profile page where he/she can see the total attendace in detail.
Suggestions : @aditya19496  @BelieveC @shubham-padia ?

**Comment by aditya-kumawat** [comment]
I think no issues in the student part.
For teacher, I am suggesting to set subjects by default according to the time table. He can choose from his subject(optional). 
E.g. If he is having class of DAA for Sem II Section A at 9am., then this will be automatically set for the time block.
Also give an option to add an extra class.
