### ISSUE TITLE
Entire codebase is prone to SQL injections.

### ISSUE THREAD

**Issue by apexkid** [GeekHaven/ProfileServer#37]
Sample code: https://github.com/GeekHaven/ProfileServer/blob/master/user.php#L38

DB can be hacked in production as there is no sanity check on the input given by the user.

**Comment by shubham-padia** [comment]
@apexkid
Parameterized queries i.e PDO syntax are used in the project, which prevents almost all sql injection cases except certain edge cases. Inspite of that, if you find any sql injection vulnerabilities, please explain in detail.

**Comment by apexkid** [comment]
@shubham-padia My bad. I missed the PDO object creation in includes. However, its still a good idea to add sanity checks in all user inputs because PDO doesn't full proof guarantee SQLi prevention. Also XSS should be prevented which can happen from user inputs. Just do a regex matching.
Ref: http://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection

Closing issue.

**Comment by shubham-padia** [comment]
@apexkid +1 for your inputs :) .
About the xss part, we already took care of that in #23  :)
Cheers .
