### ISSUE TITLE
Make a data base schema now !

### ISSUE THREAD

**Issue by adeora7** [GeekHaven/ProfileServer#9]
Make a database shcema now only. That is very important at the moment. Consult coordinators so that they can do normalizations which you might not be familiar with.

**Comment by shubham-padia** [comment]
Something like this maybe?
![db](https://cloud.githubusercontent.com/assets/13910561/16533294/4767b95c-3ff5-11e6-92a7-e6e9322ac33b.png)

**Comment by abhinavk96** [comment]
@shubham-padia I'm thinking individual table for each student
for the **attendance portion** t. whihch will have the following columns:
- Date
- Subject1
- Subject2
- Subject3
- ...
- .
- so on

there will be three possible states .. for each column, P for present, A for absent and NC for no class
By default the value will be set to No class.This way is more efficient I think cuz we will be able to avoid the whole mess of lecture ID

**Comment by BelieveC** [comment]
Schema Model for Showing Relations Between Different Entities, Remaining Fields are Described by Shubham above in his DB schema .I think Relations can be simplified as this
 [Schema](https://docs.google.com/drawings/d/10N-rEDsH1Bs0Jim3NUS7H4neXZKFLHMbNC4iMUV855c/edit?usp=sharing) .Comment to add Suggestion @aditya19496  @CosmicCoder96  @shubham-padia @adeora7

**Comment by shubham-padia** [comment]
@CosmicCoder96  making different tables for each student would take more resources and performance will suffer . Refer: http://stackoverflow.com/questions/2940384/new-table-for-every-user

**Comment by shubham-padia** [comment]
@BelieveC  In the  [schema](https://docs.google.com/drawings/d/10N-rEDsH1Bs0Jim3NUS7H4neXZKFLHMbNC4iMUV855c/edit?usp=sharing)  you  posted , for a specific lecture there will be  lots of entries with the same facultyId, subjectId , classId , so in my opinion it is not possible to eliminate the lecture table

**Comment by BelieveC** [comment]
@shubham-padia , That purpose of Recording Attendance of Specific student is fulfilled by the Attendance Table. Entries of ClassId and SubjectId etc would directly help you find weather certain student is Present in certain class or not.

**Comment by aditya-kumawat** [comment]
i will make the database schema asap. Do the frontend part till then.
